server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: haruhan-mail

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 기본값 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}
      password: ${redis_password}

logging:
  level:
    root: info

aws:
  ses:
    access-key: ${aws_access_key}
    secret-key: ${aws_secret_key}

profiles:
  active: dev