spring:
  application:
    name: haruhan-mail
  datasource:
    url: jdbc:mysql://semtle.catholic.ac.kr:3306/haruhan
    username: haruhan
    password: haruhan
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
profiles:
  active: dev